### PR TITLE
day 3 tasks 

### PR DESCRIPTION
**Pull request by iampratham29**

### CODE REVIEW

**Comment by krish8484** [comment]
Make a separate folder of your name and add these folders into it, also include the output of each file after the code(commented).

**Comment by krish8484** [comment]
Also add your day2 tasks in the same folder

**Comment by iampratham29** [comment]
Done in new pull request

**Comment by krish8484** [comment]
Have you used git pull to include files already in master?

**Comment by iampratham29** [comment]
yes, but I'm unable to see Prashant folder in mybranch

**Comment by krish8484** [comment]
You will have to add this repository as a remote(name it anything)
Then type `git pull <remote> master`

**Pull request closed without merging**
